export { NovelAPI, APIError } from './novel-api';
export type {
  User,
  Novel,
  Chapter,
  Genre,
  Comment,
  Rating,
  Bookmark,
  ReadingHistory,
  AuthPayload,
  PaginatedResponse,
  NovelQueryParams,
  ChapterQueryParams,
  CreateNovelInput,
  UpdateNovelInput,
  CreateChapterInput,
  UpdateChapterInput,
  RegisterInput,
  LoginInput,
} from './novel-api';
