export { NovelAPI, APIError } from './novel-api';
export type {
  User,
  Novel,
  Chapter,
  Genre,
  Comment,
  CommentLike,
  Rating,
  Bookmark,
  ReadingHistory,
  Follow,
  ReadingList,
  ReadingListNovel,
  Notification,
  AuthPayload,
  PaginatedResponse,
  NovelQueryParams,
  ChapterQueryParams,
  CreateNovelInput,
  UpdateNovelInput,
  CreateChapterInput,
  UpdateChapterInput,
  RegisterInput,
  LoginInput,
  CreateReadingListInput,
  UpdateReadingListInput,
  UserRole,
} from './novel-api';
